spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        ussername: sa
        password:
spring.thymeleaf.cache: false