/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Masaya' at '15/06/28 17:00' with Gradle 2.1
 *
 * @author Masaya, @date 15/06/28 17:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
